GITHUB_WEBOOK_SECRET = "<secret>"
TUMBLR_API_KEY = "<api key>"
APP_BASE = "<application path>"
DB_URL = "postgresql://localhost/bronytv"
SECRET_KEY = "<app secret key>"
GOOGLE_CALENDAR_API_KEY = "<api key>"
GOOGLE_CALENDAR_ID = "<calendar id>"
